spring.application.name=employee-consumer

server.port=7051

spring.kafka.bootstrap-servers=localhost:9092

consumer.group=employee-consumer

spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.group-id=employee-consumer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

retry.max.attempts=4
retry.backoff=2000
retry.backoff.multiplier=2

spring.kafka.consumer.max-poll-records=10
spring.kafka.consumer.properties.max.poll.interval.ms=300000
spring.kafka.consumer.properties.session.timeout.ms=60000
spring.kafka.consumer.properties.heartbeat.interval.ms=20000

topic.name=employee

management.server.port=7091
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}
