apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-producer-config-map
  namespace: green

data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:9092"
  SPRING_KAFKA_PRODUCER_PROPERTIES_COMPRESSION_TYPE: "none"