apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-metrics-agent-sa
  namespace: observability

  labels:
    app.kubernetes.io/name: prometheus-metrics-agent
    app.kubernetes.io/component: metrics-scraper
    app.kubernetes.io/part-of: observability