spring.application.name=employee-producer

server.port=7050

# Bootstrap Servers
spring.kafka.bootstrap-servers=localhost:9092

# Producer configs
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.retry.backoff.ms=100
spring.kafka.producer.batch-size=32768
spring.kafka.producer.properties.linger.ms=50

# Serializers
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Additional Kafka properties
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.compression.type=snappy
spring.kafka.producer.properties.buffer.memory=33554432
spring.kafka.producer.client-id=employee-producer-client

topic.name=employee

producer.name=employee-producer

management.server.port=7090
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}


employee.generator.interval.ms=1000