
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-consumer
  namespace: monitoring
  labels:
    app: employee-consumer
    version: v1

spec:
  replicas: 1

  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: employee-consumer
      version: v1

  template:
    metadata:
      labels:
        app: employee-consumer
        version: v1

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "7091"



    spec:

      terminationGracePeriodSeconds: 30

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000

      containers:
        - name: employee-consumer-container
          image: employee-consumer:v1
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: employee-consumer-config-map

          ports:
            - name: http
              containerPort: 7051

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits: 
              memory: "512Mi"
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 7091
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 7091
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          startupProbe:
            httpGet:
              path: "/actuator/health"
              port: 7091
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

      


