
apiVersion: v1
kind: Service
metadata:
  name: employee-consumer-prometheus
  namespace: monitoring
  labels:
    app: employee-consumer-prometheus
    version: v1

spec:
  type: LoadBalancer
  selector:
    app: employee-consumer
    version: v1
  ports:
    - name: http
      port: 7056
      targetPort: 7056